---
- name: Update apt cache
  apt: update_cache=yes cache_valid_time=3600
  become: yes

- name: Install required software
  apt: name={{ item }} state=present
  become: yes
  with_items:
    - python-mysqldb
    - mysql-server
    - php-mysql
    - python-mysqldb-dbg
    - python-software-properties

- name: Atualizar arquivo de configuracao do wordpress
  become: yes
  lineinfile:
   dest=/etc/mysql/mysql.conf.d/mysqld.cnf regexp='^bind-address = 127\.0\.0\.1' line='bind-address = 0.0.0.0'
  notify:
    - Reiniciando o MySQL

- name: Create mysql database
  become: yes
  mysql_db: 
    name={{ wp_mysql_db }} state=present login_user=root login_password=SenhaRoot

- name: Create mysql user
  become: yes
  mysql_user: name={{ wp_mysql_user }} password={{ wp_mysql_password }} priv='*.*:ALL,GRANT' state=present login_user=root login_password=SenhaRoot host=172.16.10.147
# tasks file for mysql
